# Generated by Django 4.2.1 on 2023-05-31 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vegatebles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(upload_to='images')),
                ('created_ad', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sabzavot',
                'verbose_name_plural': 'Sabzavotlar',
            },
        ),
    ]
