# Generated by Django 4.2.1 on 2023-05-31 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=255)),
                ('text', models.TextField(blank=True)),
                ('is_valid', models.BooleanField(default=False)),
                ('created_ad', models.DateField(default=True)),
            ],
        ),
    ]
