# Generated by Django 4.2.1 on 2023-05-31 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='created_ad',
            field=models.DateField(auto_now=True),
        ),
    ]
